# fly.toml (Versão FINAL e CORRIGIDA para usar o Dockerfile)

app = "pamonharia-saborosa-bot"
primary_region = "gru"

# A seção [build] foi REMOVIDA para forçar o uso do nosso Dockerfile.

[processes]
  app = "npm run start:bot"

[mounts]
  source = "wwebjs_auth_data"
  destination = "/data/wwebjs_auth"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512