# fly.toml (Versão final com CPU performance e 2GB de RAM)

app = "pamonharia-saborosa-bot"
primary_region = "gru"

[processes]
  app = "npm run start:bot"

[mounts]
  source = "wwebjs_auth_data"
  destination = "/data/wwebjs_auth"

# ATUALIZADO: Alocando os 2GB de RAM exigidos pela plataforma
[[vm]]
  cpu_kind = "performance"
  cpus = 1
  memory_mb = 2048