app = "pamonharia-saborosa-bot"
primary_region = "gru"

[build]
  builder = "heroku/builder:22"

[processes]
  app = "npm run start:bot"

[mounts]
  source = "wwebjs_auth_data"
  destination = "/data/wwebjs_auth"