# fly.toml (Versão final com CPU performance)

app = "pamonharia-saborosa-bot"
primary_region = "gru"

[processes]
  app = "npm run start:bot"

[mounts]
  source = "wwebjs_auth_data"
  destination = "/data/wwebjs_auth"

# ATUALIZADO: Pedindo uma máquina com CPU dedicada
[[vm]]
  cpu_kind = "performance"
  cpus = 1
  memory_mb = 1024